min_version = "0.115.4"
name = "GrUvTeX"
license = "MIT"
licenselink = "https://github.com/ghassbomb/GrUvTeX/blob/master/LICENSE"
description = "GrUvTeX is a LaTeX-inspired theme that utilizes the various gruvbox color schemes."
homepage = "http://ghassbomb.github.io/"
tags = [
  "python",
  "latex",
  "light",
  "minimal",
  "responsive",
  "simple",
  "gruvbox",
  "programming",
  "coding",
  "books",
  "history",
  "hugo",
  "linux",
  "macos",
]
features = ["blog"]


[author]
name = "Ghassan Shahzad"
homepage = "https://github.com/ghassbomb/"
